################################################################################
# BSD LICENSE
#
# Copyright(c) 2020-2022 Intel Corporation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#   * Neither the name of Intel Corporation nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################

---
# By default deploy AppQoS
state: present

# RDT/AppQoS repo details
rdt_repo: https://github.com/intel/intel-cmt-cat
rdt_repo_version: master

# Directory where RDT/AppQoS repo lands
appqos_path: /opt/intel/appqos_workspace

# Default appqos port
appqos_port: 5000

# Appqos run command
appqos_cmd: "WORKON_HOME=../venv/appqos_$HOSTNAME nohup pipenv run python3 ./appqos \
-c /tmp/appqos.conf --port {{ appqos_port }} > appqos.log 2>&1 &"

# Appqos directory
appqos_dir: "{{ appqos_path }}/appqos"

# Appqos ca directory
appqos_ca_dir: "{{ appqos_dir }}/ca"

# Appqos KEY file - private key
appqos_key_file: appqos.key

# Appqos CRT file - certificate
appqos_crt_file: appqos.crt

# Appqos CA crt file
appqos_ca_crt_file: ca.crt

# Cert/key files required for running appqos
appqos_ca_required_content:
  - "{{ appqos_key_file }}"
  - "{{ appqos_crt_file }}"
  - "{{ appqos_ca_crt_file }}"

  # Appqos config file
appqos_conf_path: /tmp/appqos.conf

# Appqos process regexp
appqos_proc_regexp: '^python.? \./appqos\.py'

# Appqos config file content
appqos_conf_content: |
 {
    "apps": [],
    "sstbf": {
        "configured": false
    },
    "pools": [],
    "power_profiles_expert_mode": true
 }
