sudo: required
dist: focal
before_script:
    - sudo apt-get -q update
    - sudo apt-get install -y swig cppcheck wget python3-virtualenv python3-pip clang-format codespell
    - sudo python3 -m pip install pipenv
    - wget -P /tmp/ https://raw.githubusercontent.com/torvalds/linux/184b8f7f91ca7938c09533df83ce84817e682975/scripts/checkpatch.pl && chmod a+x /tmp/checkpatch.pl
    - wget -P /tmp/ https://raw.githubusercontent.com/torvalds/linux/184b8f7f91ca7938c09533df83ce84817e682975/scripts/spelling.txt
    - wget -P /tmp/ https://raw.githubusercontent.com/torvalds/linux/184b8f7f91ca7938c09533df83ce84817e682975/scripts/const_structs.checkpatch
script:
    - make cppcheck
    - make setup-dev
    - make style CHECKPATCH=/tmp/checkpatch.pl
    - make
    - sudo make install
    - LD_LIBRARY_PATH=`pwd`/lib make -C lib/python test
    - LD_LIBRARY_PATH=`pwd`/lib make -C appqos test
    - cd lib/perl && perl Makefile.PL && make && sudo make install
language: c
compiler:
    - gcc
#    - clang
